insert into youtube_channels (vtuber_id)
     values ('miru'),
            ('ubye'),
            ('hoonie'),
            ('rayer'),
            ('rana'),
            ('shaya'),
            ('ruroro'),
            ('kwakon'),
            ('ikusen'),
            ('aoi'),
            ('usagi'),
            ('haruka'),
            ('tsmatch'),
            ('tedobear'),
            ('kurita'),
            ('asa'),
            ('kaina'),
            ('nyoro'),
            ('yuna'),
            ('yumemi');
