fn main() {
    println!("cargo:rustc-env=YOUTUBE_API_KEY0=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    println!("cargo:rustc-env=YOUTUBE_API_KEY1=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

    println!("cargo:rustc-env=FIREBASE_PROJECT_ID=XXXXXXXXX");
    println!("cargo:rustc-env=FIREBASE_WEB_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

    println!("cargo:rustc-env=FIREBASE_USER_EMAIL=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    println!("cargo:rustc-env=FIREBASE_USER_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
}
