export const symbolToCurrency = {
  "£": ["GBP", "United Kingdom Pound"],
  "¥": ["JPY", "Japan Yen"],
  "₩": ["KRW", "South Korean Won"],
  "₪": ["ILS", "Israel Shekel"],
  "€": ["EUR", "Euro"],
  "₱": ["PHP", "Philippines Peso"],
  "₹": ["INR", "India Rupee"],
  $: ["USD", "United States Dollar"],
  A$: ["AUD", "Australia Dollar"],
  AED: ["AED", "United Arab Emirates Dirham"],
  ARS: ["ARS", "Argentina Peso"],
  BAM: ["BAM", "Bosnia-Herzegovina Convertible Mark"],
  BGN: ["BGN", "Bulgaria Lev"],
  BOB: ["BOB", "Bolivia Bolíviano"],
  BYN: ["BYN", "Belarus Ruble"],
  CA$: ["CAD", "Canada Dollar"],
  CHF: ["CHF", "Switzerland Franc"],
  CLP: ["CLP", "Chile Peso"],
  COP: ["COP", "Colombia Peso"],
  CRC: ["CRC", "Costa Rica Colon"],
  CZK: ["CZK", "Czech Republic Koruna"],
  DKK: ["DKK", "Denmark Krone"],
  EGP: ["EGP", "Egypt Pound"],
  GTQ: ["GTQ", "Guatemala Quetzal"],
  HK$: ["HKD", "Hong Kong Dollar"],
  HNL: ["HNL", "Honduras Lempira"],
  HRK: ["HRK", "Croatia Kuna"],
  HUF: ["HUF", "Hungary Forint"],
  ISK: ["ISK", "Iceland Krona"],
  MX$: ["MXN", "Mexico Peso"],
  MYR: ["MYR", "Malaysia Ringgit"],
  NIO: ["NIO", "Nicaragua Cordoba"],
  NOK: ["NOK", "Norway Krone"],
  NT$: ["TWD", "Taiwan New Dollar"],
  NZ$: ["NZD", "New Zealand Dollar"],
  PEN: ["PEN", "Peru Sol"],
  PLN: ["PLN", "Poland Zloty"],
  R$: ["BRL", "Brazil Real"],
  RON: ["RON", "Romania Leu"],
  RSD: ["RSD", "Serbia Dinar"],
  RUB: ["RUB", "Russia Ruble"],
  SAR: ["SAR", "Saudi Arabia Riyal"],
  SEK: ["SEK", "Sweden Krona"],
  SGD: ["SGD", "Singapore Dollar"],
  TRY: ["TRY", "Turkey Lira"],
  ZAR: ["ZAR", "South Africa Rand"],
};

export const hexToColorName = {
  "1DE9B6FF": "Green",
  FFCA28FF: "Yellow",
  "1E88E5FF": "Blue",
  "00E5FFFF": "Light blue",
  F57C00FF: "Orange",
  E91E63FF: "Magenta",
  E62117FF: "Red",
};
