name: Web Prod

on:
  push:
    branches:
      - master
    paths:
      - web/**
      - .github/workflows/web-prod.yml

defaults:
  run:
    working-directory: web

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Run Prettier
        run: yarn prettier --check --ignore-path .gitignore 'src/**/*.{ts,js,json.html,scss}'

      - name: Build
        run: |
          sed -i "s/GIT_COMMIT_HASH/$(git rev-parse --short HEAD)/" src/environments/*
          yarn build --prod

      - name: Setup playwright
        uses: microsoft/playwright-github-action@v1

      - name: Run e2e
        continue-on-error: true
        run: |
          node e2e/server.js &
          yarn e2e

      - name: Build workers
        run: yarn tsc -P workers/tsconfig.json

      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: web
          environment: prod
